apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: examples/customer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 5005
          name: "debug"